[book]
authors = ["reichtum"]
language = "en"
multilingual = false
src = "src"
title = "English30Days"

[preprocessor.wikilinks]

[output.html]
additional-css = ["custom.css"]
mathjax-support = true

